# Generated by Django 4.0.1 on 2022-01-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_page_content_alter_page_dt_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='dt_created',
            field=models.DateTimeField(verbose_name='Date Created'),
        ),
    ]
